"""
P02 — Add education_level_harmonized to final_WM_MICS and wm_merged.parquet.

Harmonization: map education_level (country-specific codes) → 4-level ISCED scale
  0 = No education / Pre-primary
  1 = Primary
  2 = Secondary (lower + upper + vocational)
  3 = Higher / Tertiary
  NULL = sentinel / unmapped

Mapping source: MICS-WM/data/WM/education_harmonize_map.csv
(Generated by scan_education_labels.py — re-run if datasets change.)

Usage:
  python patch_education_harmonized.py db       # patch DB only
  python patch_education_harmonized.py parquet  # patch parquet only
  python patch_education_harmonized.py all      # both (parquet first)

DB status:   PENDING
Parquet status: PENDING
"""
from __future__ import annotations

import io
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import psycopg2

sys.path.insert(0, str(Path(__file__).parent))
from config import DATA_DIR

MAP_CSV = DATA_DIR / "WM" / "education_harmonize_map.csv"
PARQUET_FILE = DATA_DIR / "WM" / "processed_data" / "wm_merged.parquet"
DB_PARAMS = dict(host="localhost", port=5432, dbname="mda", user="lichao")

CANONICAL_VAR = "education_level_harmonized"
CANONICAL_TEXT = (
    "Harmonized education level (ISCED 4-level): "
    "0=No education, 1=Primary, 2=Secondary, 3=Higher"
)


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _load_map() -> pd.DataFrame:
    """
    Load the harmonization map.
    Returns DataFrame with columns: dataset_name, edu_val (str), harmonized (0/1/2/3 or NaN)
    """
    df = pd.read_csv(MAP_CSV, dtype={"edu_val": str})
    # -1 (sentinel) → NaN so DB stores NULL
    df.loc[df["harmonized"] == -1, "harmonized"] = np.nan
    return df[["dataset_name", "edu_val", "harmonized"]]


def _connect() -> psycopg2.extensions.connection:
    conn = psycopg2.connect(**DB_PARAMS)
    conn.autocommit = False
    return conn


# ---------------------------------------------------------------------------
# DB step
# ---------------------------------------------------------------------------

def patch_db() -> None:
    map_df = _load_map()
    valid = map_df[map_df["harmonized"].notna()].copy()
    valid["harmonized"] = valid["harmonized"].astype(float)
    print(f"Mapping rows (valid ISCED 0-3): {len(valid):,}")
    print(f"Mapping rows (→ NULL):           {map_df['harmonized'].isna().sum():,}")

    conn = _connect()
    try:
        with conn.cursor() as cur:
            # 1. Add column if absent
            cur.execute("""
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'final_WM_MICS'
                  AND column_name = 'education_level_harmonized'
            """)
            col_exists = cur.fetchone() is not None
            if not col_exists:
                print("Adding column education_level_harmonized ...")
                cur.execute(
                    'ALTER TABLE "final_WM_MICS" '
                    'ADD COLUMN education_level_harmonized DOUBLE PRECISION'
                )
                conn.commit()
                print("  Column added.")
            else:
                print("Column already exists, will overwrite values.")

            # 2. Create temp mapping table and COPY data
            cur.execute("""
                CREATE TEMP TABLE _edu_map (
                    dataset_name TEXT,
                    education_level_raw TEXT,
                    harmonized DOUBLE PRECISION
                )
            """)
            buf = io.StringIO()
            valid.rename(columns={"edu_val": "education_level_raw"}).to_csv(
                buf, index=False, header=False, na_rep="\\N"
            )
            buf.seek(0)
            cur.copy_expert(
                "COPY _edu_map (dataset_name, education_level_raw, harmonized) "
                "FROM STDIN WITH (FORMAT CSV, NULL '\\N')",
                buf,
            )
            conn.commit()
            print(f"Temp map loaded ({len(valid):,} rows).")

            # 3. UPDATE main table
            print("Updating education_level_harmonized ...")
            cur.execute("""
                UPDATE "final_WM_MICS" w
                SET education_level_harmonized = m.harmonized
                FROM _edu_map m
                WHERE w.dataset_name = m.dataset_name
                  AND w.education_level = m.education_level_raw
            """)
            updated = cur.rowcount
            conn.commit()
            print(f"  Rows updated: {updated:,}")

            # 4. Verify
            cur.execute("""
                SELECT education_level_harmonized, COUNT(*) AS n
                FROM "final_WM_MICS"
                GROUP BY education_level_harmonized
                ORDER BY education_level_harmonized
            """)
            print("\n  Distribution:")
            labels = {0: "0=None", 1: "1=Primary", 2: "2=Secondary",
                      3: "3=Higher", None: "NULL"}
            for val, n in cur.fetchall():
                lbl = labels.get(int(val) if val is not None else None, str(val))
                print(f"    {lbl:<15} {n:>10,}")

        # 5. Update ind_que
        print("\nUpdating ind_que_WM_MICS ...")
        _update_ind_que(conn)

    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    print("\nDB patch done.")


def _update_ind_que(conn: psycopg2.extensions.connection) -> None:
    with conn.cursor() as cur:
        # Remove any existing harmonized entries to avoid duplicates
        cur.execute("""
            DELETE FROM "ind_que_WM_MICS"
            WHERE canonical_varname = 'education_level_harmonized'
        """)
        deleted = cur.rowcount

        # Insert one derived row per dataset that has education_level
        cur.execute("""
            INSERT INTO "ind_que_WM_MICS"
                (canonical_varname, dataset_name, column_in_raw_sav,
                 column_label_in_english, source_kind, measure_type, canonical_text)
            SELECT DISTINCT
                'education_level_harmonized',
                dataset_name,
                'education_level',
                'Derived: ISCED 4-level from education_level',
                'derived',
                'woman_background',
                %s
            FROM "ind_que_WM_MICS"
            WHERE canonical_varname = 'education_level'
        """, (CANONICAL_TEXT,))
        inserted = cur.rowcount
        conn.commit()
        print(f"  ind_que: removed {deleted} old rows, inserted {inserted} derived rows.")


# ---------------------------------------------------------------------------
# Parquet step
# ---------------------------------------------------------------------------

def patch_parquet() -> None:
    map_df = _load_map()
    # Build lookup: (dataset_name, edu_val_str) → harmonized
    map_df["edu_val"] = map_df["edu_val"].astype(str)
    lookup = map_df.set_index(["dataset_name", "edu_val"])["harmonized"]

    print(f"Reading {PARQUET_FILE} ...")
    df = pd.read_parquet(PARQUET_FILE)

    # education_level may be float or str in parquet
    edu = df["education_level"].astype(str)
    keys = list(zip(df["dataset_name"], edu))
    harmonized = pd.array([lookup.get(k, np.nan) for k in keys], dtype="Float64")
    df["education_level_harmonized"] = harmonized

    n_valid = pd.notna(harmonized).sum()
    print(f"  education_level_harmonized non-null: {n_valid:,} / {len(df):,}")
    print("  Value counts:")
    for v, n in pd.Series(harmonized).value_counts(dropna=False).sort_index().items():
        print(f"    {v}: {n:,}")

    df.to_parquet(PARQUET_FILE, index=False)
    print("  Parquet saved.")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    if not MAP_CSV.exists():
        print(f"ERROR: mapping file not found: {MAP_CSV}")
        print("Run scan_education_labels.py first.")
        sys.exit(1)

    mode = sys.argv[1] if len(sys.argv) > 1 else "all"
    if mode in ("parquet", "all"):
        patch_parquet()
    if mode in ("db", "all"):
        patch_db()
    print("\nAll done.")


if __name__ == "__main__":
    main()
