"""
P04 — Add media_tv_frequency_harmonized to final_WM_MICS and wm_merged.parquet.

Harmonized 4-level frequency scale:
  0 = Never / Not at all
  1 = Less than once a week (incl. "at least once a month")
  2 = At least once a week (but not every day)
  3 = Almost every day / Every day
  NULL = sentinel (8/9/99, incoherent) or unmapped

Mapping source: MICS-WM/data/WM/media_tv_harmonize_map.csv
(Generated by scan_media_tv_labels.py — re-run if datasets change.)

Usage:
  python patch_media_tv_harmonized.py db
  python patch_media_tv_harmonized.py parquet
  python patch_media_tv_harmonized.py all
"""
from __future__ import annotations

import io
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import psycopg2

sys.path.insert(0, str(Path(__file__).parent))
from config import DATA_DIR

MAP_CSV = DATA_DIR / "WM" / "media_tv_harmonize_map.csv"
PARQUET_FILE = DATA_DIR / "WM" / "processed_data" / "wm_merged.parquet"
DB_PARAMS = dict(host="localhost", port=5432, dbname="mda", user="lichao")

CANONICAL_TEXT = (
    "Harmonized TV-watching frequency (4-level): "
    "0=Never, 1=<once/week, 2=>=once/week, 3=Almost every day"
)


def _load_map() -> pd.DataFrame:
    df = pd.read_csv(MAP_CSV, dtype={"raw_value": str})
    df.loc[df["harmonized"] == -1, "harmonized"] = np.nan
    return df[["dataset_name", "raw_value", "harmonized"]]


def _connect() -> psycopg2.extensions.connection:
    conn = psycopg2.connect(**DB_PARAMS)
    conn.autocommit = False
    return conn


# ---------------------------------------------------------------------------
# DB step
# ---------------------------------------------------------------------------

def patch_db() -> None:
    map_df = _load_map()
    valid = map_df[map_df["harmonized"].notna()].copy()
    valid["harmonized"] = valid["harmonized"].astype(float)

    # raw_value in the CSV is a float string like "0.0"; normalize to match DB
    def _norm(x):
        try:
            return str(int(float(x)))
        except (ValueError, TypeError):
            return str(x).strip()

    valid["tv_val_norm"] = valid["raw_value"].map(_norm)

    print(f"Mapping rows (valid 0-3): {len(valid):,}")
    print(f"Mapping rows (→ NULL):    {map_df['harmonized'].isna().sum():,}")

    conn = _connect()
    try:
        with conn.cursor() as cur:
            # 1. Add column if absent
            cur.execute("""
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'final_WM_MICS'
                  AND column_name = 'media_tv_frequency_harmonized'
            """)
            if cur.fetchone() is None:
                print("Adding column media_tv_frequency_harmonized ...")
                cur.execute(
                    'ALTER TABLE "final_WM_MICS" '
                    'ADD COLUMN media_tv_frequency_harmonized DOUBLE PRECISION'
                )
                conn.commit()
            else:
                print("Column already exists, will overwrite.")

            # 2. Temp mapping table
            # media_tv_frequency in WM is DOUBLE PRECISION; match on numeric value
            cur.execute("""
                CREATE TEMP TABLE _tv_map (
                    dataset_name  TEXT,
                    tv_val        DOUBLE PRECISION,
                    harmonized    DOUBLE PRECISION
                )
            """)
            valid["tv_val_num"] = pd.to_numeric(valid["tv_val_norm"], errors="coerce")
            valid_num = valid[valid["tv_val_num"].notna()]

            buf = io.StringIO()
            valid_num[["dataset_name", "tv_val_num", "harmonized"]].to_csv(
                buf, index=False, header=False, na_rep="\\N"
            )
            buf.seek(0)
            cur.copy_expert(
                "COPY _tv_map (dataset_name, tv_val, harmonized) "
                "FROM STDIN WITH (FORMAT CSV, NULL '\\N')",
                buf,
            )
            conn.commit()
            print(f"Temp map loaded ({len(valid_num):,} rows).")

            # 3. UPDATE
            print("Updating media_tv_frequency_harmonized ...")
            cur.execute("""
                UPDATE "final_WM_MICS" w
                SET media_tv_frequency_harmonized = m.harmonized
                FROM _tv_map m
                WHERE w.dataset_name = m.dataset_name
                  AND w.media_tv_frequency = m.tv_val
            """)
            updated = cur.rowcount
            conn.commit()
            print(f"  Rows updated: {updated:,}")

            # 4. Verify
            cur.execute("""
                SELECT media_tv_frequency_harmonized, COUNT(*) AS n
                FROM "final_WM_MICS"
                GROUP BY media_tv_frequency_harmonized
                ORDER BY media_tv_frequency_harmonized
            """)
            print("\n  Distribution:")
            labels = {0: "0=Never", 1: "1=<weekly", 2: "2=≥weekly", 3: "3=~daily", None: "NULL"}
            for val, n in cur.fetchall():
                lbl = labels.get(int(val) if val is not None else None, str(val))
                print(f"    {lbl:<12} {n:>12,}")

        # 5. Update ind_que
        print("\nUpdating ind_que_WM_MICS ...")
        _update_ind_que(conn)

    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    print("\nDB patch done.")


def _update_ind_que(conn: psycopg2.extensions.connection) -> None:
    with conn.cursor() as cur:
        cur.execute("""
            DELETE FROM "ind_que_WM_MICS"
            WHERE canonical_varname = 'media_tv_frequency_harmonized'
        """)
        cur.execute("""
            INSERT INTO "ind_que_WM_MICS"
                (canonical_varname, dataset_name, column_in_raw_sav,
                 column_label_in_english, source_kind, measure_type, canonical_text)
            SELECT DISTINCT
                'media_tv_frequency_harmonized',
                dataset_name,
                'media_tv_frequency',
                'Derived: harmonized TV frequency (4-level) from media_tv_frequency',
                'derived',
                'media_exposure',
                %s
            FROM "ind_que_WM_MICS"
            WHERE canonical_varname = 'media_tv_frequency'
        """, (CANONICAL_TEXT,))
        conn.commit()
        print(f"  ind_que: inserted {cur.rowcount} derived rows.")


# ---------------------------------------------------------------------------
# Parquet step
# ---------------------------------------------------------------------------

def patch_parquet() -> None:
    map_df = _load_map()

    def _norm(x):
        try:
            return int(float(x))
        except (ValueError, TypeError):
            return None

    map_df["tv_val_num"] = map_df["raw_value"].map(_norm)
    lookup = (
        map_df[map_df["tv_val_num"].notna()]
        .set_index(["dataset_name", "tv_val_num"])["harmonized"]
    )

    print(f"Reading {PARQUET_FILE} ...")
    df = pd.read_parquet(PARQUET_FILE)

    tv = pd.to_numeric(df["media_tv_frequency"], errors="coerce")
    tv_int = tv.map(lambda x: int(x) if pd.notna(x) else None)
    keys = list(zip(df["dataset_name"], tv_int))
    harmonized = pd.array([lookup.get(k, np.nan) for k in keys], dtype="Float64")
    df["media_tv_frequency_harmonized"] = harmonized

    n_valid = pd.notna(harmonized).sum()
    print(f"  media_tv_frequency_harmonized non-null: {n_valid:,} / {len(df):,}")
    print("  Value counts:")
    for v, n in pd.Series(harmonized).value_counts(dropna=False).sort_index().items():
        print(f"    {v}: {n:,}")

    df.to_parquet(PARQUET_FILE, index=False)
    print("  Parquet saved.")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    if not MAP_CSV.exists():
        print(f"ERROR: mapping file not found: {MAP_CSV}")
        print("Run scan_media_tv_labels.py first.")
        sys.exit(1)

    mode = sys.argv[1] if len(sys.argv) > 1 else "all"
    if mode in ("db", "all"):
        patch_db()
    if mode in ("parquet", "all"):
        patch_parquet()
    print("\nAll done.")


if __name__ == "__main__":
    main()
