"""
P09 step 4 — Sync education_years columns to PostgreSQL.

1. Snapshot patch-derived ind_que rows (WM, CH — HL's derived rows come from yaml)
2. Re-upload final_WM/HL/CH from the patched parquets (existing upload scripts)
3. Re-insert snapshots
4. Insert derived ind_que rows for the new variables
5. Verify

Usage: python sync_p09_to_db.py
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pandas as pd
import psycopg2

_PROJECT_ROOT = Path(__file__).parent.parent.parent
DB_PARAMS = dict(host="localhost", port=5432, dbname="mda", user="lichao")
PY = str(_PROJECT_ROOT / ".venv" / "bin" / "python")

MODULES = {
    "WM": {
        "upload": _PROJECT_ROOT / "MICS-WM" / "src" / "upload_wm_to_postgres.py",
        "final": "final_WM_MICS", "ind": "ind_que_WM_MICS",
        "parquet": _PROJECT_ROOT / "MICS-WM" / "data" / "WM" / "processed_data" / "wm_merged.parquet",
        "snapshot_derived": True,
        "new_vars": [("education_years",
                      "Derived: years of schooling from education_level + education_grade "
                      "+ WB school-system durations (P09)"),
                     ("education_years_estimated",
                      "Derived: 1 = education_years is a level-midpoint estimate (grade missing)")],
        "source_cols": "education_level+education_grade",
        "measure_type": "woman_background",
    },
    "HL": {
        "upload": _PROJECT_ROOT / "MICS-HL" / "src" / "upload_hl_to_postgres.py",
        "final": "final_HL_MICS", "ind": "ind_que_HL_MICS",
        "parquet": _PROJECT_ROOT / "MICS-HL" / "data" / "HL" / "processed_data" / "hl_merged.parquet",
        "snapshot_derived": False,
        "new_vars": [("education_years",
                      "Derived: years of schooling from highest_education_level + "
                      "highest_grade_completed + WB school-system durations (P09)"),
                     ("education_years_estimated",
                      "Derived: 1 = education_years is a level-midpoint estimate (grade missing)")],
        "source_cols": "highest_education_level+highest_grade_completed",
        "measure_type": "household_member_background",
    },
    "CH": {
        "upload": _PROJECT_ROOT / "MICS-CH" / "src" / "upload_ch_to_postgres.py",
        "final": "final_CH_MICS", "ind": "ind_que_CH_MICS",
        "parquet": _PROJECT_ROOT / "MICS-CH" / "data" / "CH" / "processed_data" / "ch_merged.parquet",
        "snapshot_derived": True,
        "new_vars": [("mother_education_years",
                      "Derived: mother's years of schooling — WM-linked, HL fallback, "
                      "coarse 4-level midpoint last resort (P09)"),
                     ("mother_education_years_estimated",
                      "Derived: 1 = estimated (level midpoint or coarse fallback)")],
        "source_cols": "mother_caretaker_line_number→WM/HL",
        "measure_type": "child_background",
    },
}


def snapshot_derived(conn, mod: dict) -> pd.DataFrame | None:
    if not mod["snapshot_derived"]:
        return None
    q = f'SELECT * FROM "{mod["ind"]}" WHERE source_kind = \'derived\''
    df = pd.read_sql(q, conn)
    print(f"  snapshot {mod['ind']}: {len(df)} derived rows")
    return df


def reinsert_derived(conn, mod: dict, snap: pd.DataFrame | None) -> None:
    if snap is None or snap.empty:
        return
    # yaml-derived rows are regenerated by the upload; only reinsert the
    # patch-derived canonicals that the rebuild does not know about
    with conn.cursor() as cur:
        cur.execute(f'''SELECT DISTINCT canonical_varname FROM "{mod["ind"]}"
                        WHERE source_kind = 'derived' ''')
        rebuilt = {r[0] for r in cur.fetchall()}
    snap = snap[~snap.canonical_varname.isin(rebuilt)]
    if snap.empty:
        print(f"  nothing to reinsert into {mod['ind']}")
        return
    cols = list(snap.columns)
    col_sql = ", ".join(f'"{c}"' for c in cols)
    ph = ", ".join(["%s"] * len(cols))
    with conn.cursor() as cur:
        cur.executemany(
            f'INSERT INTO "{mod["ind"]}" ({col_sql}) VALUES ({ph})',
            snap.where(pd.notna(snap), None).values.tolist(),
        )
    conn.commit()
    print(f"  reinserted {len(snap)} derived rows into {mod['ind']}")


def insert_new_derived(conn, mod: dict) -> None:
    var0 = mod["new_vars"][0][0]
    datasets = pd.read_parquet(mod["parquet"], columns=["dataset_name", var0])
    ds_list = sorted(datasets.loc[datasets[var0].notna(), "dataset_name"].unique())
    with conn.cursor() as cur:
        for var, text in mod["new_vars"]:
            cur.execute(f'DELETE FROM "{mod["ind"]}" WHERE canonical_varname = %s', (var,))
            cur.executemany(
                f'''INSERT INTO "{mod["ind"]}"
                    (canonical_varname, dataset_name, column_in_raw_sav,
                     column_label_in_english, source_kind, measure_type, canonical_text)
                    VALUES (%s, %s, %s, %s, 'derived', %s, %s)''',
                [(var, ds, mod["source_cols"], text, mod["measure_type"], text)
                 for ds in ds_list],
            )
    conn.commit()
    print(f"  {mod['ind']}: inserted derived rows for "
          f"{[v for v, _ in mod['new_vars']]} × {len(ds_list)} datasets")


def verify(conn, mod: dict) -> None:
    var0 = mod["new_vars"][0][0]
    with conn.cursor() as cur:
        cur.execute(f'SELECT COUNT(*), COUNT("{var0}") FROM "{mod["final"]}"')
        total, nn = cur.fetchone()
    print(f"  {mod['final']}: {total:,} rows, {var0} non-null {nn:,}")


def main() -> None:
    for name in ("WM", "HL", "CH"):
        mod = MODULES[name]
        print(f"\n===== {name} =====")
        conn = psycopg2.connect(**DB_PARAMS)
        snap = snapshot_derived(conn, mod)
        conn.close()

        print(f"  uploading via {mod['upload'].name} ...")
        r = subprocess.run([PY, str(mod["upload"])], capture_output=True, text=True)
        if r.returncode != 0:
            print(r.stdout[-2000:])
            print(r.stderr[-2000:])
            sys.exit(f"{name} upload failed")

        conn = psycopg2.connect(**DB_PARAMS)
        reinsert_derived(conn, mod, snap)
        insert_new_derived(conn, mod)
        verify(conn, mod)
        conn.close()

    print("\nAll modules synced.")


if __name__ == "__main__":
    main()
