"""
P03 — Add mother_education_harmonized to final_CH_MICS and ch_merged.parquet.

ISCED 4-level:
  0 = No education / Pre-primary
  1 = Primary
  2 = Secondary (lower + upper + vocational)
  3 = Higher / Tertiary
  NULL = sentinel / unmapped

Mapping source: MICS-CH/data/CH/mother_education_harmonize_map.csv
(Generated by scan_mother_education_labels.py — re-run if datasets change.)

Usage:
  python patch_mother_education_harmonized.py db
  python patch_mother_education_harmonized.py parquet
  python patch_mother_education_harmonized.py all

DB status:   PENDING
Parquet status: PENDING
"""
from __future__ import annotations

import io
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import psycopg2

sys.path.insert(0, str(Path(__file__).parent))
from config import DATA_DIR

MAP_CSV = DATA_DIR / "CH" / "mother_education_harmonize_map.csv"
PARQUET_FILE = DATA_DIR / "CH" / "processed_data" / "ch_merged.parquet"
DB_PARAMS = dict(host="localhost", port=5432, dbname="mda", user="lichao")

CANONICAL_TEXT = (
    "Harmonized mother education level (ISCED 4-level): "
    "0=No education, 1=Primary, 2=Secondary, 3=Higher"
)


def _load_map() -> pd.DataFrame:
    df = pd.read_csv(MAP_CSV, dtype={"edu_val": str})
    df.loc[df["harmonized"] == -1, "harmonized"] = np.nan
    return df[["dataset_name", "edu_val", "harmonized"]]


def _connect() -> psycopg2.extensions.connection:
    conn = psycopg2.connect(**DB_PARAMS)
    conn.autocommit = False
    return conn


# ---------------------------------------------------------------------------
# DB step
# ---------------------------------------------------------------------------

def patch_db() -> None:
    map_df = _load_map()
    valid = map_df[map_df["harmonized"].notna()].copy()
    valid["harmonized"] = valid["harmonized"].astype(float)
    print(f"Mapping rows (valid ISCED 0-3): {len(valid):,}")
    print(f"Mapping rows (→ NULL):           {map_df['harmonized'].isna().sum():,}")

    # mother_education in CH is numeric; convert edu_val back to float for matching
    valid["edu_val_num"] = pd.to_numeric(valid["edu_val"], errors="coerce")
    valid = valid[valid["edu_val_num"].notna()].copy()

    conn = _connect()
    try:
        with conn.cursor() as cur:
            # 1. Add column if absent
            cur.execute("""
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'final_CH_MICS'
                  AND column_name = 'mother_education_harmonized'
            """)
            if cur.fetchone() is None:
                print("Adding column mother_education_harmonized ...")
                cur.execute(
                    'ALTER TABLE "final_CH_MICS" '
                    'ADD COLUMN mother_education_harmonized DOUBLE PRECISION'
                )
                conn.commit()
            else:
                print("Column already exists, will overwrite.")

            # 2. Temp mapping table
            cur.execute("""
                CREATE TEMP TABLE _medu_map (
                    dataset_name      TEXT,
                    mother_edu_val    DOUBLE PRECISION,
                    harmonized        DOUBLE PRECISION
                )
            """)
            buf = io.StringIO()
            valid[["dataset_name", "edu_val_num", "harmonized"]].to_csv(
                buf, index=False, header=False, na_rep="\\N"
            )
            buf.seek(0)
            cur.copy_expert(
                "COPY _medu_map (dataset_name, mother_edu_val, harmonized) "
                "FROM STDIN WITH (FORMAT CSV, NULL '\\N')",
                buf,
            )
            conn.commit()
            print(f"Temp map loaded ({len(valid):,} rows).")

            # 3. UPDATE
            print("Updating mother_education_harmonized ...")
            cur.execute("""
                UPDATE "final_CH_MICS" w
                SET mother_education_harmonized = m.harmonized
                FROM _medu_map m
                WHERE w.dataset_name = m.dataset_name
                  AND w.mother_education = m.mother_edu_val
            """)
            updated = cur.rowcount
            conn.commit()
            print(f"  Rows updated: {updated:,}")

            # 4. Verify
            cur.execute("""
                SELECT mother_education_harmonized, COUNT(*) AS n
                FROM "final_CH_MICS"
                GROUP BY mother_education_harmonized
                ORDER BY mother_education_harmonized
            """)
            print("\n  Distribution:")
            labels = {0: "0=None", 1: "1=Primary", 2: "2=Secondary",
                      3: "3=Higher", None: "NULL"}
            for val, n in cur.fetchall():
                lbl = labels.get(int(val) if val is not None else None, str(val))
                print(f"    {lbl:<15} {n:>10,}")

        # 5. Update ind_que
        print("\nUpdating ind_que_CH_MICS ...")
        _update_ind_que(conn)

    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()

    print("\nDB patch done.")


def _update_ind_que(conn: psycopg2.extensions.connection) -> None:
    with conn.cursor() as cur:
        cur.execute("""
            DELETE FROM "ind_que_CH_MICS"
            WHERE canonical_varname = 'mother_education_harmonized'
        """)
        cur.execute("""
            INSERT INTO "ind_que_CH_MICS"
                (canonical_varname, dataset_name, column_in_raw_sav,
                 column_label_in_english, source_kind, measure_type, canonical_text)
            SELECT DISTINCT
                'mother_education_harmonized',
                dataset_name,
                'mother_education',
                'Derived: ISCED 4-level from mother_education',
                'derived',
                'mother_background',
                %s
            FROM "ind_que_CH_MICS"
            WHERE canonical_varname = 'mother_education'
        """, (CANONICAL_TEXT,))
        conn.commit()
        print(f"  ind_que: inserted {cur.rowcount} derived rows.")


# ---------------------------------------------------------------------------
# Parquet step
# ---------------------------------------------------------------------------

def patch_parquet() -> None:
    map_df = _load_map()
    map_df["edu_val_num"] = pd.to_numeric(map_df["edu_val"], errors="coerce")
    # lookup: (dataset_name, float_code) → harmonized
    lookup = (map_df[map_df["edu_val_num"].notna()]
              .set_index(["dataset_name", "edu_val_num"])["harmonized"])

    print(f"Reading {PARQUET_FILE} ...")
    df = pd.read_parquet(PARQUET_FILE)

    edu = pd.to_numeric(df["mother_education"], errors="coerce")
    keys = list(zip(df["dataset_name"], edu))
    harmonized = pd.array([lookup.get(k, np.nan) for k in keys], dtype="Float64")
    df["mother_education_harmonized"] = harmonized

    n_valid = pd.notna(harmonized).sum()
    print(f"  mother_education_harmonized non-null: {n_valid:,} / {len(df):,}")
    print("  Value counts:")
    for v, n in pd.Series(harmonized).value_counts(dropna=False).sort_index().items():
        print(f"    {v}: {n:,}")

    df.to_parquet(PARQUET_FILE, index=False)
    print("  Parquet saved.")


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main() -> None:
    if not MAP_CSV.exists():
        print(f"ERROR: mapping file not found: {MAP_CSV}")
        print("Run scan_mother_education_labels.py first.")
        sys.exit(1)

    mode = sys.argv[1] if len(sys.argv) > 1 else "all"
    if mode in ("parquet", "all"):
        patch_parquet()
    if mode in ("db", "all"):
        patch_db()
    print("\nAll done.")


if __name__ == "__main__":
    main()
